name: Docker Image CI

on:
  push:
    branches: [ "aditya" ]
  pull_request:
    branches: [ "aditya" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: set env
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
