name: Docker Image CI

on:
  push:
    branches: [ "aditya" ]
  pull_request:
    branches: [ "aditya" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: docker build --build-arg NGROK_AUTH_TOKEN=$Env:NGROK_AUTH_TOKEN . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: echo
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: echo $NGROK_AUTH_TOKEN
