name: Docker Image CI

on:
  push:
    branches: [ "aditya" ]
  pull_request:
    branches: [ "aditya" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: download ngrok
      run: wget -O ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
    - name: download unzip
      run:  sudo apt install ssh wget unzip -y
    - name: ls
      run:  ls -a
    - name: unzip
      run:  unzip ngrok.zip
    - name: ls2
      run:  ls -a
    - name: Build the Docker image
      run: ./ngrok authtoken ${{ secrets.ngrok_auth_token }}
    - name: start ngrok
      run: ./ngrok tcp 22
